### ISSUE TITLE
Issue with "Is It Racist?"

### ISSUE THREAD

**Issue by vosss** [zposten/postenz_web#1]
When using the app, entering the name "Zach Posten" returns the same thing every time, and its always wrong. 
![Example use](https://cloud.githubusercontent.com/assets/1350045/12245739/04ce2796-b870-11e5-915b-503be3c129eb.png)

**Comment by zposten** [comment]
I apologize @vosss but the internet seems to simply have a glowing opinion of this guy.  There's nothing I can do.
